server:
  port: 9090

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"

spring:
  application:
    name: Client Management Service
  profiles:
    active: Test
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop #validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
